blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/nafiskabbo/bangla-type#readme
    about: README and docs
  - name: Discussions
    url: https://github.com/nafiskabbo/bangla-type/discussions
    about: Ask questions and discuss ideas
